routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'KampusController@index');

Route::resource('kampus', 'KampusController');
Route::resource('kampus2', 'Kampus2Controller');
Route::resource('kriteria', 'KriteriaController');
Route::resource('subkriteria', 'SubKriteriaController');

Route::group(['prefix' => 'bobot'], function(){
  Route::get('/', 'BobotController@index')->name('bobot.index');

  Route::group(['prefix' => 'ahp'], function(){
    Route::get('/', 'BobotController@ahp')->name('bobot.ahp');
    Route::get('form', 'BobotController@ahpform')->name('bobot.ahp.form');
    Route::post('/', 'BobotController@ahpstore')->name('bobot.ahp.store');

    Route::group(['prefix' => 'sub'], function(){
      Route::get('/{kriteriaId}/form', 'BobotController@subForm')->name('bobot.ahp.sub.form');
      Route::post('/', 'BobotController@substore')->name('bobot.ahp.sub.store');
    });
  });

  Route::group(['prefix' => 'saw'], function(){
    Route::get('/', 'BobotController@saw')->name('bobot.saw');
    Route::get('form', 'BobotController@sawform')->name('bobot.saw.form');
    Route::post('/', 'BobotController@sawstore')->name('bobot.saw.store');
  });
});

Route::group(['prefix' => 'penilaian'], function(){
  Route::get('/', 'PenilaianController@index')->name('penilaian.index');

  Route::group(['prefix' => 'ahp'], function(){
    Route::get('/', 'PenilaianAHPController@index')->name('penilaian.ahp.index');
    Route::get('/form', 'PenilaianAHPController@form')->name('penilaian.ahp.form');
    Route::get('/{id}/view', 'PenilaianAHPController@view')->name('penilaian.ahp.view');
    Route::post('/', 'PenilaianAHPController@store')->name('penilaian.ahp.store');
  });

  Route::group(['prefix' => 'saw'], function(){
    Route::get('/', 'PenilaianSAWController@index')->name('penilaian.saw.index');
    Route::get('/form', 'PenilaianSAWController@form')->name('penilaian.saw.form');
    Route::get('/{id}/view', 'PenilaianSAWController@view')->name('penilaian.saw.view');
    Route::post('/', 'PenilaianSAWController@store')->name('penilaian.saw.store');
  });
});

app/SubKriteria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubKriteria extends Model
{
    protected $table = 'sub_kriteria';
    protected $fillable = [
    	'nama', 'bobot', 'kriteriaId'
    ];
    public $timestamps = false;

    public function kriteria(){
    	return $this->belongsTo('App\Kriteria', 'kriteriaId');
    }
}

app/Http/Controllers/SubKriteriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\SubKriteriaRequest;

use App\Kriteria;
use App\SubKriteria;

class SubKriteriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['no'] = 1;
        $data['subkriteria'] = SubKriteria::all();
        return view('page.subkriteria.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['kriteria'] = Kriteria::where('kategori', '1')->get();
        $data['subkriteria'] = (object)[
            'id' => '',
            'nama' => '',
            'kriteriaId' => ''
        ];
        return view('page.subkriteria.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SubKriteriaRequest $request)
    {
        SubKriteria::create([
            'nama' => $request->nama,
            'kriteriaId' => $request->kriteriaId
        ]);

        return redirect()->route('subkriteria.index')->with('success', 'Simpan data berhasil!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kriteria'] = Kriteria::all();
        $data['subkriteria'] = SubKriteria::find($id);

        return view('page.subkriteria.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SubKriteriaRequest $request, $id)
    {
        $data = Subkriteria::find($id);
        $data->nama = $request->nama;

        if($data->kriteriaId  != $request->kriteriaId){
            $data->bobot = null;    
        }

        $data->kriteriaId = $request->kriteriaId;

        $data->save();

        return redirect()->route('subkriteria.index')->with('success', 'Update data berhasil!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = SubKriteria::find($id);
        $data->delete();
        return redirect()->route('subkriteria.index')->with('success', 'Delete data berhasil!');
    }
}

resources/views/page/subkriteria/form.blade.php
@extends('master')

@section('content')

<h5>Form Sub Kriteria (AHP)</h5>
<div class="row">
	<div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('subkriteria.index') }}" class="btn btn-success">Kembali</a>
      </div>
      <div class="card-body">
        <form action="{{ (empty($subkriteria->id))?route('subkriteria.store'):route('subkriteria.update', ['subkriterium' => $subkriteria->id]) }}" method="POST">
          @csrf
          @if(!empty($subkriteria->id))
            @method('PUT')
          @endif

          <div class="form-group">
            <label for="nama">Nama</label>
            <input type="text" name="nama" id="nama" class="form-control {{ ($errors->has('nama'))?'is-invalid':'' }}" value="{{ $subkriteria->nama }}">

            <!-- error -->
            @if($errors->has('nama'))
              <small class="text-danger">*{{ $errors->first('nama') }}</small>
            @endif
          </div>

          <div class="form-group">
            <label for="kriteriaId">Kriteria</label>
            <select name="kriteriaId" id="kriteriaId" class="form-control {{ ($errors->has('kriteriaId'))?'is-invalid':'' }}">
              <option value="">Pilih</option>
              @foreach($kriteria as $kr)
                <option value="{{ $kr->id }}" {{ ($subkriteria->kriteriaId == $kr->id)?'selected':'' }}>{{ $kr->nama }}</option>
              @endforeach
            </select>

            <!-- error -->
            @if($errors->has('kriteriaId'))
              <small class="text-danger">*{{ $errors->first('kriteriaId') }}</small>
            @endif
          </div>
          <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/page/subkriteria/index.blade.php
@extends('master')

@section('content')

<h5>Data Sub Kriteria (AHP)</h5>
<div class="row">
	<div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('subkriteria.create') }}" class="btn btn-primary">Tambah Data</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered dataTable">
            <thead>
              <tr>
                <th>No</th>
                <th>Kriteria</th>
                <th>Nama</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach($subkriteria as $row)
                <tr>
                  <td>{{ $no++ }}</td>
                  <td>{{ $row->kriteria->nama }}</td>
                  <td>{{ $row->nama }}</td>
                  <td>
                    <form action="{{ route('subkriteria.destroy', ['subkriterium' => $row->id]) }}" method="POST" onSubmit="return confirm('Anda yakin ingin menghapus data?')">
                      @csrf
                      @method('DELETE')
                      <a href="{{ route('subkriteria.edit', ['subkriterium' => $row->id]) }}" class="btn btn-success btn-sm">Edit</a>
                      <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                    </form>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection