routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'KampusController@index');

Route::resource('kampus', 'KampusController');
Route::resource('kampus2', 'Kampus2Controller');
Route::resource('kriteria', 'KriteriaController');
Route::resource('subkriteria', 'SubKriteriaController');

Route::group(['prefix' => 'bobot'], function(){
  Route::get('/', 'BobotController@index')->name('bobot.index');

  Route::group(['prefix' => 'ahp'], function(){
    Route::get('/', 'BobotController@ahp')->name('bobot.ahp');
    Route::get('form', 'BobotController@ahpform')->name('bobot.ahp.form');
    Route::post('/', 'BobotController@ahpstore')->name('bobot.ahp.store');

    Route::group(['prefix' => 'sub'], function(){
      Route::get('/{kriteriaId}/form', 'BobotController@subForm')->name('bobot.ahp.sub.form');
      Route::post('/', 'BobotController@substore')->name('bobot.ahp.sub.store');
    });
  });

  Route::group(['prefix' => 'saw'], function(){
    Route::get('/', 'BobotController@saw')->name('bobot.saw');
    Route::get('form', 'BobotController@sawform')->name('bobot.saw.form');
    Route::post('/', 'BobotController@sawstore')->name('bobot.saw.store');
  });
});

Route::group(['prefix' => 'penilaian'], function(){
  Route::get('/', 'PenilaianController@index')->name('penilaian.index');

  Route::group(['prefix' => 'ahp'], function(){
    Route::get('/', 'PenilaianAHPController@index')->name('penilaian.ahp.index');
    Route::get('/form', 'PenilaianAHPController@form')->name('penilaian.ahp.form');
    Route::get('/{id}/view', 'PenilaianAHPController@view')->name('penilaian.ahp.view');
    Route::post('/', 'PenilaianAHPController@store')->name('penilaian.ahp.store');
  });

  Route::group(['prefix' => 'saw'], function(){
    Route::get('/', 'PenilaianSAWController@index')->name('penilaian.saw.index');
    Route::get('/form', 'PenilaianSAWController@form')->name('penilaian.saw.form');
    Route::get('/{id}/view', 'PenilaianSAWController@view')->name('penilaian.saw.view');
    Route::post('/', 'PenilaianSAWController@store')->name('penilaian.saw.store');
  });
});

app/Kampus2.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kampus2 extends Model
{
    protected $table = 'kampus2';
    protected $fillable = [
        'NamaKampus', 'NamaRektor', 'Alamat', 'NoTelp', 'JumlahFakultas', 'TanggalOperasi'
    ];
    protected $primaryKey = 'IdKampus';

    public $timestamps = false;
}

app/Http/Controllers/Kampus2Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\Kampus2Request;

use App\Kampus2;

class Kampus2Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['no'] = 1;
        $data['kampus2'] = Kampus2::all();
        return view('page.kampus2.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['kampus2'] = (object)[
            'IdKampus' => '',
            'NamaKampus' => '',
            'NamaRektor' => '',
            'Alamat' => '',
            'NoTelp' => '',
            'JumlahFakultas' => '',
            'TanggalOperasi' => ''
        ];
        return view('page.kampus2.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Kampus2Request $request)
    {
        Kampus2::create([
            'NamaKampus' => $request->NamaKampus,
            'NamaRektor' => $request->NamaRektor,
            'Alamat' => $request->Alamat,
            'NoTelp' => $request->NoTelp,
            'JumlahFakultas' => $request->JumlahFakultas,
            'TanggalOperasi' => $request->TanggalOperasi
        ]);

        return redirect()->route('kampus2.index')->with('success', 'Simpan data berhasil!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kampus2'] = Kampus2::find($id);

        return view('page.kampus2.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Kampus2Request $request, $id)
    {
        $data = Kampus2::find($id);
        $data->NamaKampus = $request->NamaKampus;
        $data->NamaRektor = $request->NamaRektor;
        $data->Alamat = $request->Alamat;
        $data->NoTelp = $request->NoTelp;
        $data->JumlahFakultas = $request->JumlahFakultas;
        $data->TanggalOperasi = $request->TanggalOperasi;
        $data->save();

        return redirect()->route('kampus2.index')->with('success', 'Update data berhasil!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Kampus2::find($id);
        $data->delete();
        return redirect()->route('kampus2.index')->with('success', 'Delete data berhasil!');
    }
}

resources/views/page/kampus2/form.blade.php
@extends('master')

@section('content')

<h5>Form Kampus2</h5>
<div class="row">
	<div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('kampus2.index') }}" class="btn btn-success">Kembali</a>
      </div>
      <div class="card-body">
        <form action="{{ (empty($kampus2->IdKampus))?route('kampus2.store'):route('kampus2.update', ['kampus2' => $kampus2->IdKampus]) }}" method="POST">
          @csrf
          @if(!empty($kampus2->IdKampus))
            @method('PUT')
          @endif

          <div class="form-group">
            <label for="NamaKampus">Nama</label>
            <input type="text" name="NamaKampus" id="NamaKampus" class="form-control {{ ($errors->has('NamaKampus'))?'is-invalid':'' }}" value="{{ $kampus2->NamaKampus }}">

            <!-- error -->
            @if($errors->has('NamaKampus'))
              <small class="text-danger">*{{ $errors->first('NamaKampus') }}</small>
            @endif
          </div>

          <div class="form-group">
            <label for="NamaRektor">Rektor</label>
            <input type="text" name="NamaRektor" id="NamaRektor" class="form-control {{ ($errors->has('NamaRektor'))?'is-invalid':'' }}" value="{{ $kampus2->NamaRektor }}">

            <!-- error -->
            @if($errors->has('NamaRektor'))
              <small class="text-danger">*{{ $errors->first('NamaRektor') }}</small>
            @endif
          </div>

          <div class="form-group">
            <label for="Alamat">Alamat</label>
            <textarea name="Alamat" id="Alamat" rows="5" class="form-control {{ ($errors->has('Alamat'))?'is-invalid':'' }}">{{ $kampus2->Alamat }}</textarea>

            <!-- error -->
            @if($errors->has('Alamat'))
              <small class="text-danger">*{{ $errors->first('Alamat') }}</small>
            @endif
          </div>
          
          <div class="form-group">
            <label for="NoTelp">Telp</label>
            <input type="number" name="NoTelp" id="NoTelp" class="form-control {{ ($errors->has('NoTelp'))?'is-invalid':'' }}" value="{{ $kampus2->NoTelp }}">

            <!-- error -->
            @if($errors->has('NoTelp'))
              <small class="text-danger">*{{ $errors->first('NoTelp') }}</small>
            @endif
          </div>

          <div class="form-group">
            <label for="JumlahFakultas">Jumlah Fakultas</label>
            <input type="number" name="JumlahFakultas" id="JumlahFakultas" class="form-control {{ ($errors->has('JumlahFakultas'))?'is-invalid':'' }}" value="{{ $kampus2->JumlahFakultas }}">

            <!-- error -->
            @if($errors->has('JumlahFakultas'))
              <small class="text-danger">*{{ $errors->first('JumlahFakultas') }}</small>
            @endif
          </div>

          <div class="form-group">
            <label for="TanggalOperasi">Tanggal Operasi</label>
            <input type="date" name="TanggalOperasi" id="TanggalOperasi" class="form-control {{ ($errors->has('TanggalOperasi'))?'is-invalid':'' }}" value="{{ $kampus2->TanggalOperasi }}">

            <!-- error -->
            @if($errors->has('TanggalOperasi'))
              <small class="text-danger">*{{ $errors->first('TanggalOperasi') }}</small>
            @endif
          </div>
          <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/page/kampus2/index.blade.php
@extends('master')

@section('content')

<h5>Data Kampus2</h5>
<div class="row">
	<div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('kampus2.create') }}" class="btn btn-primary">Tambah Data</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered dataTable">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Rektor</th>
                <th>Alamat</th>
                <th>No Telp</th>
                <th>Jml Fakultas</th>
                <th>Tanggal Operasi</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach($kampus2 as $row)
                <tr>
                  <td>{{ $no++ }}</td>
                  <td>{{ $row->NamaKampus }}</td>
                  <td>{{ $row->NamaRektor }}</td>
                  <td>{{ $row->Alamat }}</td>
                  <td>{{ $row->NoTelp }}</td>
                  <td>{{ $row->JumlahFakultas }}</td>
                  <td>{{ $row->TanggalOperasi }}</td>
                  <td>
                    <form action="{{ route('kampus2.destroy', ['kampus2' => $row->IdKampus]) }}" method="POST" onSubmit="return confirm('Anda yakin ingin menghapus data?')">
                      @csrf
                      @method('DELETE')
                      <a href="{{ route('kampus2.edit', ['kampus2' => $row->IdKampus]) }}" class="btn btn-success btn-sm">Edit</a>
                      <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                    </form>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection