routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'KampusController@index');

Route::resource('kampus', 'KampusController');
Route::resource('kampus2', 'Kampus2Controller');
Route::resource('kriteria', 'KriteriaController');
Route::resource('subkriteria', 'SubKriteriaController');

Route::group(['prefix' => 'bobot'], function(){
  Route::get('/', 'BobotController@index')->name('bobot.index');

  Route::group(['prefix' => 'ahp'], function(){
    Route::get('/', 'BobotController@ahp')->name('bobot.ahp');
    Route::get('form', 'BobotController@ahpform')->name('bobot.ahp.form');
    Route::post('/', 'BobotController@ahpstore')->name('bobot.ahp.store');

    Route::group(['prefix' => 'sub'], function(){
      Route::get('/{kriteriaId}/form', 'BobotController@subForm')->name('bobot.ahp.sub.form');
      Route::post('/', 'BobotController@substore')->name('bobot.ahp.sub.store');
    });
  });

  Route::group(['prefix' => 'saw'], function(){
    Route::get('/', 'BobotController@saw')->name('bobot.saw');
    Route::get('form', 'BobotController@sawform')->name('bobot.saw.form');
    Route::post('/', 'BobotController@sawstore')->name('bobot.saw.store');
  });
});

Route::group(['prefix' => 'penilaian'], function(){
  Route::get('/', 'PenilaianController@index')->name('penilaian.index');

  Route::group(['prefix' => 'ahp'], function(){
    Route::get('/', 'PenilaianAHPController@index')->name('penilaian.ahp.index');
    Route::get('/form', 'PenilaianAHPController@form')->name('penilaian.ahp.form');
    Route::get('/{id}/view', 'PenilaianAHPController@view')->name('penilaian.ahp.view');
    Route::post('/', 'PenilaianAHPController@store')->name('penilaian.ahp.store');
  });

  Route::group(['prefix' => 'saw'], function(){
    Route::get('/', 'PenilaianSAWController@index')->name('penilaian.saw.index');
    Route::get('/form', 'PenilaianSAWController@form')->name('penilaian.saw.form');
    Route::get('/{id}/view', 'PenilaianSAWController@view')->name('penilaian.saw.view');
    Route::post('/', 'PenilaianSAWController@store')->name('penilaian.saw.store');
  });
});

app/Kampus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kampus extends Model
{
    protected $table = 'kampus';
    protected $fillable = [
    	'nama', 'jk', 'tglLahir', 'alamat'
    ];

    public function penilaian(){
    	return $this->hasMany('App\Penilaian', 'kampusId');
    }
}

app/Http/Controllers/KampusController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\KampusRequest;

use App\Kampus;

class KampusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['no'] = 1;
        $data['kampus'] = Kampus::all();
        return view('page.kampus.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['kampus'] = (object)[
            'id' => '',
            'nama' => '',
            'alamat' => ''
        ];
        return view('page.kampus.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KampusRequest $request)
    {
        Kampus::create([
            'nama' => $request->nama,
            'alamat' => $request->alamat
        ]);

        return redirect()->route('kampus.index')->with('success', 'Simpan data berhasil!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kampus'] = Kampus::find($id);

        return view('page.kampus.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KampusRequest $request, $id)
    {
        $data = Kampus::find($id);
        $data->nama = $request->nama;
        $data->alamat = $request->alamat;
        $data->save();

        return redirect()->route('kampus.index')->with('success', 'Update data berhasil!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Kampus::find($id);
        $data->delete();
        return redirect()->route('kampus.index')->with('success', 'Delete data berhasil!');
    }
}

resources/views/page/kampus/form.blade.php
@extends('master')

@section('content')

<h5>Form Kampus</h5>
<div class="row">
	<div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('kampus.index') }}" class="btn btn-success">Kembali</a>
      </div>
      <div class="card-body">
        <form action="{{ (empty($kampus->id))?route('kampus.store'):route('kampus.update', ['kampus' => $kampus->id]) }}" method="POST">
          @csrf
          @if(!empty($kampus->id))
            @method('PUT')
          @endif

          <div class="form-group">
            <label for="nama">Nama</label>
            <input type="text" name="nama" id="nama" class="form-control {{ ($errors->has('nama'))?'is-invalid':'' }}" value="{{ $kampus->nama }}">

            <!-- error -->
            @if($errors->has('nama'))
              <small class="text-danger">*{{ $errors->first('nama') }}</small>
            @endif
          </div>

          <div class="form-group">
            <label for="alamat">Alamat</label>
            <textarea name="alamat" id="alamat" rows="5" class="form-control {{ ($errors->has('alamat'))?'is-invalid':'' }}">{{ $kampus->alamat }}</textarea>

            <!-- error -->
            @if($errors->has('alamat'))
              <small class="text-danger">*{{ $errors->first('alamat') }}</small>
            @endif
          </div>
          <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/page/kampus/index.blade.php
@extends('master')

@section('content')

<h5>Data Kampus</h5>
<div class="row">
	<div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('kampus.create') }}" class="btn btn-primary">Tambah Data</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered dataTable">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Alamat</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach($kampus as $row)
                <tr>
                  <td>{{ $no++ }}</td>
                  <td>{{ $row->nama }}</td>
                  <td>{{ $row->alamat }}</td>
                  <td>
                    <form action="{{ route('kampus.destroy', ['kampus' => $row->id]) }}" method="POST" onSubmit="return confirm('Anda yakin ingin menghapus data?')">
                      @csrf
                      @method('DELETE')
                      <a href="{{ route('kampus.edit', ['kampus' => $row->id]) }}" class="btn btn-success btn-sm">Edit</a>
                      <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                    </form>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection